import Head from "next/head";
import { SigninProvider } from "../context/signin";
import { PanelAsideProvider } from "@/context/panel_aside";
import { PanelSectionProvider } from "@/context/panel_section";
import { CreateTravelProvider } from "@/context/create_travel";
import Main from "@/components/main";
import { DarkModeProvider } from "@/context/dark_mode";
import { SupportProvider } from "@/context/support";

export default function Home() {
	return (
		<>
			<Head>
				<title>Apolo</title>
				<meta name="description" content="Generated by create next app" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<DarkModeProvider>
				<PanelAsideProvider>
					<SigninProvider>
						<PanelSectionProvider>
							<CreateTravelProvider>
								<SupportProvider>
									<Main></Main>
								</SupportProvider>
							</CreateTravelProvider>
						</PanelSectionProvider>
					</SigninProvider>
				</PanelAsideProvider>
			</DarkModeProvider>
		</>
	);
}
