import Head from "next/head";
import { Signin } from "@/components/signin";
import { SigninContext, SigninProvider } from "@/context/Signin";
import { useContext } from "react";

export default function Home() {
	const isSignin = useContext(SigninContext);
	return (
		<>
			<Head>
				<title>Apolo</title>
				<meta name="description" content="Generated by create next app" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
				/>
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
				<link
					href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;400;700&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<SigninProvider>
				<main>{!isSignin && <Signin />}</main>
			</SigninProvider>
		</>
	);
}
