import Head from "next/head";
import { Signin } from "@/components/signin";
import { useState } from "react";

export default function Home() {
	const [isSignin, setIsSignin] = useState(false);

	return (
		<>
			<Head>
				<title>Apolo</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>{!isSignin && <Signin />}</main>
		</>
	);
}
